### ISSUE TITLE
Date ISO format ?

### ISSUE THREAD

**Issue by raed667** [pandageeks/apimocka#1]
When using "date.future" is there a way to get a date in the standard ISO format?

**Comment by ghostffcode** [comment]
Hi @RaedsLab, I just noticed that the dates are not in ISO format. I'll be working on a fix in the next few hours. Update will be posted here when ready.

**Comment by ghostffcode** [comment]
An update has been published. To get ISO values on the date namespace, prefix it with `ISO:`

In this specific use case, instead of `date.future` use `ISO:date.future`

**Comment by raed667** [comment]
Thank you for the quick response ! Works perfectly!
