### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by raed667** [pandageeks/apimocka#2]
I'm having this issue : 

```Failed to load https://mockd.co/zyk9dcv5tro/tasks: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://localhost' is therefore not allowed access.```

Is there a way to allow this to work ?

**Comment by ghostffcode** [comment]
Thank you for bringing this to my notice. I'll look into the `CORS` configuration ASAP

**Comment by ghostffcode** [comment]
This issue have been rectified, please do let me know if you experience any difficulty with it.
